---
#Provision some instances:
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/all

  tasks:
  - name: Launch webserver instances
    ntnx: >
     user="{{ ntnx_user }}"
     password="{{ ntnx_password }}"
     image="{{ centos_server_v7}}"
     instance_tags="{'ansible_group':'{{ tag_lbservers }}', 'type':'{{ instance_type }}', 'group':'{{ security_group }}'}"
     count="{{ ntnx_instance_count }}"
    register: ntnx

  - name: Launch database instance
    ec2: >
     user="{{ ntnx_user }}"
     password="{{ ntnx_password }}"
     image="{{ centos_server_v7}}"
     instance_tags="{'ansible_group':'{{ tag_lbservers }}', 'type':'{{ instance_type }}', 'group':'{{ security_group }}'}"
     count="{{ ntnx_instance_count }}"
     count="1"
    register: ec2

  - name: Launch load balancing instance
    ntnx: >
     image="{{ ntnx_image }}
     instance_tags="{'ansible_group':'{{ tag_lbservers }}', 'type':'{{ instance_type }}', 'group':'{{ security_group }}'}"
     count="1"
    register: ntnx

  - name: Wait for SSH to come up
    local_action: wait_for host={{ item.public_dns_name }}
      port=22 delay=60 timeout=320 state=started
    with_items: "{{ ec2.instances }}"
